### ISSUE TITLE
example

### ISSUE THREAD

**Issue by volga629** [sam-github/netfilter-lua#4]
Hello Sam,
I looking on netfilter-lua lib and trying understand how it monitor queue for changes.
My goal is setup utility as following.

1. create queue  with NFQUEUE
2. monitor created queue for arriving packet.
3. copy data from arrived packet (source and destination ip protocol reason ...)
4. do verdict (insert into iptables with action).
5. delete processed packet.

All this in efforts create block utility for sircata ips

architecture

suricata  Alert/Drop --> NFQUEUE 10 redirect packet--> utility NFQUEUE 12 (action)

**Comment by sam-github** [comment]
I haven't used this in a long time, but the lua API closely follows the nfqueue API, look upstream at the Linux docs to understand how the API works.
